
//-----------------------------------------------USER-----------------------------------------------

POST http://localhost:5000/auth/user/register
Content-Type: application/json

{
    "phone": "0387126867",
    "name": "tian",
    "address": "NamDinh",
    "password": "tung811"
}

###
POST  http://localhost:5000/auth/user/login
Content-Type: application/json

{
    "phone": "0387126034",
    "password": "123"
}

###
GET http://localhost:5000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmIwODMzNDM5NDMxOTcxMDE4NzMzMjUiLCJpYXQiOjE2NTYwNTA0ODd9.cdqvHycG7B9Pl2CsuVmD4zQP826C-Y5YnBowFZLugk8

###
PUT http://localhost:5000/auth/user/62b083343943197101873325
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmIwODMzNDM5NDMxOTcxMDE4NzMzMjUiLCJpYXQiOjE2NTYwNTA0ODd9.cdqvHycG7B9Pl2CsuVmD4zQP826C-Y5YnBowFZLugk8
Content-Type: application/json

{
    "phone" : "0387126034",
    "name": "Bùi Quang Tu",
    "address": "Tân Triều, Thanh Trì, Hà Nội" 
}

//-----------------------------------------------STORE-----------------------------------------------

###
GET http://localhost:5000/auth/store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZUlkIjoiNjI5Nzk5ZGJmODllZDVkN2M1MTI2NGZhIiwiaWF0IjoxNjU0MjM4MTc4fQ.70Pewby4W9lUaUghnKgNULKVJPoYXHeJi2Qaze62dbE

###
PUT http://localhost:5000/auth/store/629799dbf89ed5d7c51264fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZUlkIjoiNjI5Nzk5ZGJmODllZDVkN2M1MTI2NGZhIiwiaWF0IjoxNjU0MjQwMjUyfQ.DkW1bdPhDTbhQJISaEWFCMZgRYA25tt7wm2aR1dtxtE
Content-Type: application/json

{
    "phone" : "0387126036",
    "name": "Bún chả Hà Nội 1",
    "address": "Tân Triều, Thanh Trì, Hà Nội 1", 
    "categories": ["bun", "pho", "chao"]
}

###
POST http://localhost:5000/auth/store/register
Content-Type: application/json

{
    "address": "HaNoi",
    "categories": ["Xôi", "Cháo", "Chè"],
    "confirmPassword": "123",
    "name": "a ấ",
    "password": "123",
    "phone": "0387126043",
    "timeClose": "20:00:00",
    "timeOpen": "07:00:00"
}

###
POST http://localhost:5000/auth/store/login
Content-Type: application/json

{
    "phone": "0387126034",
    "password": "123"
}

//-----------------------------------------------FOODS-----------------------------------------------

###
POST http://localhost:5000/foods/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZUlkIjoiNjI5YjVjMTYxNWNkYjcwYjllODE1OWYwIiwiaWF0IjoxNjU0MzUxNzgyfQ.crZu0sS91zwpCC7Ahmu4hJL62nOqbg5GRw0QKqPcP_w
Content-Type: application/json

{
    "name": "bun1",
    "image": "path image",
    "price": 30000
}

//-----------------------------------------------ORDER-----------------------------------------------

###
GET http://localhost:5000/orders
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYzY2I4ZTA4NmRhYzA0MmQwZTVjNzYiLCJpYXQiOjE2NTM2NjQ1MzV9.sddLn6AqY2aD6DChHa4E60kRjMxXOfXYQzo6rOip2oE

###
POST http://localhost:5000/orders/add
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmIwODMzNDM5NDMxOTcxMDE4NzMzMjUiLCJpYXQiOjE2NTYwNTA0ODd9.cdqvHycG7B9Pl2CsuVmD4zQP826C-Y5YnBowFZLugk8
Content-Type: application/json

{
    "restaurant": "629ff7d9b1a2b515753aaf32",
    "foods": [{"name": "food1"}, {"name": "food2"}],
    "totalPrice": "65000"
}

###
GET http://localhost:5000/orders/getOrderApp
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmIwODMzNDM5NDMxOTcxMDE4NzMzMjUiLCJpYXQiOjE2NTYwNTA0ODd9.cdqvHycG7B9Pl2CsuVmD4zQP826C-Y5YnBowFZLugk8
Content-Type: application/json

###
GET http://localhost:5000/orders/getOrderWeb
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZUlkIjoiNjI5ZjlmZWY1MDMzODk0NDYxMzA3YjBiIiwiaWF0IjoxNjU0NjI4MzM1fQ.on7dcXYnKGOiy31kdqdA3Ko5a555g3IWEyOmLLY6QEs
Content-Type: application/json

###
PUT http://localhost:5000/orders/update/62b723e83072bbf6179afd32
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZUlkIjoiNjI5ZjlmZWY1MDMzODk0NDYxMzA3YjBiIiwiaWF0IjoxNjU0NjI4MzM1fQ.on7dcXYnKGOiy31kdqdA3Ko5a555g3IWEyOmLLY6QEs
Content-Type: application/json

{
    "status" : "CHUẨN BỊ"
}

//-----------------------------------------------UPLOAD-----------------------------------------------

###
POST http://localhost:5000/images/delete
Content-Type: application/json

{
    "path": "http://localhost:3000/upload/store/028e8b2d-130d-42f1-9bab-be8fe8f07b4d-1654327518975.png"
}

//-----------------------------------------------GET-----------------------------------------------
###
GET http://localhost:5000/get/stores/Chè
# Content-Type: application/json

# {
#     "category": "Bún"
# }


###
GET http://localhost:5000/get/stores/search/p